<!DOCTYPE html>
<html>
<head>
    <title>ptest html report</title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
    <meta name="description" content="ptest test results."/>
    <link href="report.css" rel="stylesheet" type="text/css"/>
    <style id="extra-style" type="text/css"></style>
</head>
<body>
<div id="meta">
    Generated by <a href="https://pypi.python.org/pypi/ptest">ptest</a> at 2017-06-01 22:52:23.791034
    <br/><span id="system-info">AndersondeMacBook-Pro.local / Python 3.5.3 / Darwin-16.6.0-x86_64-i386-64bit</span>
</div>
<h1>Test Results</h1>

<div class="main-container">
    <div class="panel navigation">
        <div class="panel-heading">
            <div class="filter-btn all" filter="all">ALL<span class="badge"></span></div>
            <div class="filter-btn passed" filter="passed">PASS<span class="badge"></span></div>
            <div class="filter-btn failed" filter="failed">FAIL<span class="badge"></span></div>
            <div class="filter-btn skipped" filter="skipped">SKIP<span class="badge"></span></div>
        </div>
        <div class="panel-body">
            <div class="toolbar">
                <span class="expand-all">ExpandAll</span>
                <span class="collapse-all">CollapseAll</span>
            </div>
            <div class="tree">
                <ul></ul>
            </div>
        </div>
        <div id="splitter"></div>
    </div>
    <div class="panel detail">
        <div class="panel-heading">
            <span class="text"></span>
        </div>
        <div class="panel-body"></div>
    </div>
</div>
<script type="text/javascript" src="report.js"></script>
<script type="text/javascript">
    // init test suite data
    var testSuite = {"fullName": "DefaultSuite", "elapsedTime": 27.577648, "type": "suite", "skipped": 0, "failed": 1, "passed": 0, "testModules": [{"fullName": "autotest", "type": "module", "failed": 1, "testClasses": [], "passed": 0, "testModules": [{"fullName": "autotest.cases", "type": "module", "failed": 1, "testClasses": [], "passed": 0, "testModules": [{"fullName": "autotest.cases.test_login", "type": "module", "failed": 1, "testClasses": [{"fullName": "autotest.cases.test_login.LoginTest", "type": "class", "runGroup": null, "endTime": "2017-06-01 22:52:23.773363", "skipped": 0, "startTime": "2017-06-01 22:51:56.196525", "total": 1, "elapsedTime": 27.576838, "runMode": "singleline", "testCases": [{"fullName": "autotest.cases.test_login.LoginTest.check_login_success", "group": "DEFAULT", "type": "case", "test": {"fullName": "autotest.cases.test_login.LoginTest.check_login_success@Test", "fixtureType": "Test", "type": "fixture", "screenshots": [{"source": "Web&nbsp;Driver", "path": "autotest.cases.test_login.LoginTest.check_login_success@Test-1.png"}], "elapsedTime": 27.573866, "logs": [{"message": "Failed&nbsp;with&nbsp;following&nbsp;message:<br/>Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last):<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.local/lib/python3.5/site-packages/ptest/testexecutor.py&quot;,&nbsp;line&nbsp;383,&nbsp;in&nbsp;run_test<br/>&nbsp;&nbsp;&nbsp;&nbsp;self.test_fixture.test_fixture_ref.__call__()<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/testcode/mynewthinking/autotest/cases/test_login.py&quot;,&nbsp;line&nbsp;19,&nbsp;in&nbsp;check_login_success<br/>&nbsp;&nbsp;&nbsp;&nbsp;login&nbsp;=&nbsp;Login()<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/testcode/mynewthinking/autotest/Base.py&quot;,&nbsp;line&nbsp;22,&nbsp;in&nbsp;__init__<br/>&nbsp;&nbsp;&nbsp;&nbsp;self.driver&nbsp;=&nbsp;webdriver.Remote('http://localhost:4723/wd/hub',&nbsp;self.capabilities)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.local/lib/python3.5/site-packages/appium/webdriver/webdriver.py&quot;,&nbsp;line&nbsp;36,&nbsp;in&nbsp;__init__<br/>&nbsp;&nbsp;&nbsp;&nbsp;super(WebDriver,&nbsp;self).__init__(command_executor,&nbsp;desired_capabilities,&nbsp;browser_profile,&nbsp;proxy,&nbsp;keep_alive)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py&quot;,&nbsp;line&nbsp;98,&nbsp;in&nbsp;__init__<br/>&nbsp;&nbsp;&nbsp;&nbsp;self.start_session(desired_capabilities,&nbsp;browser_profile)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py&quot;,&nbsp;line&nbsp;188,&nbsp;in&nbsp;start_session<br/>&nbsp;&nbsp;&nbsp;&nbsp;response&nbsp;=&nbsp;self.execute(Command.NEW_SESSION,&nbsp;parameters)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py&quot;,&nbsp;line&nbsp;252,&nbsp;in&nbsp;execute<br/>&nbsp;&nbsp;&nbsp;&nbsp;self.error_handler.check_response(response)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py&quot;,&nbsp;line&nbsp;194,&nbsp;in&nbsp;check_response<br/>&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;exception_class(message,&nbsp;screen,&nbsp;stacktrace)<br/>selenium.common.exceptions.WebDriverException:&nbsp;Message:&nbsp;An&nbsp;unknown&nbsp;server-side&nbsp;error&nbsp;occurred&nbsp;while&nbsp;processing&nbsp;the&nbsp;command.&nbsp;Original&nbsp;error:&nbsp;Error&nbsp;occured&nbsp;while&nbsp;starting&nbsp;App.&nbsp;Original&nbsp;error:&nbsp;com.ef.core.engage.englishtown/com.ef.core.engage.ui.screens.activity.EnglishTownLoginActivity&nbsp;or&nbsp;com.ef.core.engage.englishtown.com.ef.core.engage.ui.screens.activity.EnglishTownLoginActivity&nbsp;never&nbsp;started<br/><br/>", "level": "error"}, {"message": "Failed&nbsp;to&nbsp;take&nbsp;the&nbsp;screenshot.<br/>Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last):<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.local/lib/python3.5/site-packages/ptest/testexecutor.py&quot;,&nbsp;line&nbsp;383,&nbsp;in&nbsp;run_test<br/>&nbsp;&nbsp;&nbsp;&nbsp;self.test_fixture.test_fixture_ref.__call__()<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/testcode/mynewthinking/autotest/cases/test_login.py&quot;,&nbsp;line&nbsp;19,&nbsp;in&nbsp;check_login_success<br/>&nbsp;&nbsp;&nbsp;&nbsp;login&nbsp;=&nbsp;Login()<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/testcode/mynewthinking/autotest/Base.py&quot;,&nbsp;line&nbsp;22,&nbsp;in&nbsp;__init__<br/>&nbsp;&nbsp;&nbsp;&nbsp;self.driver&nbsp;=&nbsp;webdriver.Remote('http://localhost:4723/wd/hub',&nbsp;self.capabilities)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.local/lib/python3.5/site-packages/appium/webdriver/webdriver.py&quot;,&nbsp;line&nbsp;36,&nbsp;in&nbsp;__init__<br/>&nbsp;&nbsp;&nbsp;&nbsp;super(WebDriver,&nbsp;self).__init__(command_executor,&nbsp;desired_capabilities,&nbsp;browser_profile,&nbsp;proxy,&nbsp;keep_alive)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py&quot;,&nbsp;line&nbsp;98,&nbsp;in&nbsp;__init__<br/>&nbsp;&nbsp;&nbsp;&nbsp;self.start_session(desired_capabilities,&nbsp;browser_profile)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py&quot;,&nbsp;line&nbsp;188,&nbsp;in&nbsp;start_session<br/>&nbsp;&nbsp;&nbsp;&nbsp;response&nbsp;=&nbsp;self.execute(Command.NEW_SESSION,&nbsp;parameters)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py&quot;,&nbsp;line&nbsp;252,&nbsp;in&nbsp;execute<br/>&nbsp;&nbsp;&nbsp;&nbsp;self.error_handler.check_response(response)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py&quot;,&nbsp;line&nbsp;194,&nbsp;in&nbsp;check_response<br/>&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;exception_class(message,&nbsp;screen,&nbsp;stacktrace)<br/>selenium.common.exceptions.WebDriverException:&nbsp;Message:&nbsp;An&nbsp;unknown&nbsp;server-side&nbsp;error&nbsp;occurred&nbsp;while&nbsp;processing&nbsp;the&nbsp;command.&nbsp;Original&nbsp;error:&nbsp;Error&nbsp;occured&nbsp;while&nbsp;starting&nbsp;App.&nbsp;Original&nbsp;error:&nbsp;com.ef.core.engage.englishtown/com.ef.core.engage.ui.screens.activity.EnglishTownLoginActivity&nbsp;or&nbsp;com.ef.core.engage.englishtown.com.ef.core.engage.ui.screens.activity.EnglishTownLoginActivity&nbsp;never&nbsp;started<br/><br/><br/>During&nbsp;handling&nbsp;of&nbsp;the&nbsp;above&nbsp;exception,&nbsp;another&nbsp;exception&nbsp;occurred:<br/><br/>Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last):<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.local/lib/python3.5/site-packages/ptest/screencapturer.py&quot;,&nbsp;line&nbsp;337,&nbsp;in&nbsp;take_screenshot<br/>&nbsp;&nbsp;&nbsp;&nbsp;f.write(web_driver.get_screenshot_as_png())<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py&quot;,&nbsp;line&nbsp;863,&nbsp;in&nbsp;get_screenshot_as_png<br/>&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py&quot;,&nbsp;line&nbsp;873,&nbsp;in&nbsp;get_screenshot_as_base64<br/>&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self.execute(Command.SCREENSHOT)['value']<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py&quot;,&nbsp;line&nbsp;250,&nbsp;in&nbsp;execute<br/>&nbsp;&nbsp;&nbsp;&nbsp;response&nbsp;=&nbsp;self.command_executor.execute(driver_command,&nbsp;params)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/site-packages/selenium/webdriver/remote/remote_connection.py&quot;,&nbsp;line&nbsp;462,&nbsp;in&nbsp;execute<br/>&nbsp;&nbsp;&nbsp;&nbsp;path&nbsp;=&nbsp;string.Template(command_info[1]).substitute(params)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/string.py&quot;,&nbsp;line&nbsp;129,&nbsp;in&nbsp;substitute<br/>&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self.pattern.sub(convert,&nbsp;self.template)<br/>&nbsp;&nbsp;File&nbsp;&quot;/Users/anderson/.pyenv/versions/3.5.3/lib/python3.5/string.py&quot;,&nbsp;line&nbsp;119,&nbsp;in&nbsp;convert<br/>&nbsp;&nbsp;&nbsp;&nbsp;val&nbsp;=&nbsp;mapping[named]<br/>TypeError:&nbsp;'NoneType'&nbsp;object&nbsp;is&nbsp;not&nbsp;subscriptable<br/>", "level": "warning"}], "description": "", "status": "failed", "endTime": "2017-06-01 22:52:23.772664", "name": "check_login_success", "startTime": "2017-06-01 22:51:56.198798"}, "tags": [], "endTime": "2017-06-01 22:52:23.772907", "startTime": "2017-06-01 22:51:56.197275", "elapsedTime": 27.575632, "description": "", "beforeMethod": {"fullName": "autotest.cases.test_login.LoginTest.check_login_success@BeforeMethod", "fixtureType": "BeforeMethod", "type": "fixture", "screenshots": [], "elapsedTime": 0.000424, "logs": [], "description": "Prepare test data.", "status": "passed", "endTime": "2017-06-01 22:51:56.197841", "name": "setup_data", "startTime": "2017-06-01 22:51:56.197417"}, "status": "failed", "name": "check_login_success"}], "description": "", "passed": 0, "failed": 1, "name": "LoginTest"}], "passed": 0, "testModules": [], "skipped": 0, "name": "test_login", "total": 1}], "skipped": 0, "name": "cases", "total": 1}], "skipped": 0, "name": "autotest", "total": 1}], "endTime": "2017-06-01 22:52:23.773592", "name": "DefaultSuite", "startTime": "2017-06-01 22:51:56.195944", "total": 1};
</script>
</body>
</html>